/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard.users'
import { Route as AuthenticatedDashboardArticlesRouteImport } from './routes/_authenticated/dashboard.articles'
import { Route as AuthenticatedDashboardAiToolsRouteImport } from './routes/_authenticated/dashboard.ai-tools'
import { Route as AuthenticatedDashboardAiDraftRouteImport } from './routes/_authenticated/dashboard.ai-draft'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/dashboard.users.index'
import { Route as AuthenticatedDashboardArticlesIndexRouteImport } from './routes/_authenticated/dashboard.articles.index'
import { Route as AuthenticatedDashboardUsersIdRouteImport } from './routes/_authenticated/dashboard.users.$id'
import { Route as AuthenticatedDashboardArticlesNewRouteImport } from './routes/_authenticated/dashboard.articles.new'
import { Route as AuthenticatedDashboardArticlesIdEditRouteImport } from './routes/_authenticated/dashboard.articles.$id.edit'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardsRoute = EditorialStandardsRouteImport.update({
  id: '/editorial-standards',
  path: '/editorial-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticlesRoute =
  AuthenticatedDashboardArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiToolsRoute =
  AuthenticatedDashboardAiToolsRouteImport.update({
    id: '/ai-tools',
    path: '/ai-tools',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiDraftRoute =
  AuthenticatedDashboardAiDraftRouteImport.update({
    id: '/ai-draft',
    path: '/ai-draft',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardUsersRoute,
  } as any)
const AuthenticatedDashboardArticlesIndexRoute =
  AuthenticatedDashboardArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardArticlesRoute,
  } as any)
const AuthenticatedDashboardUsersIdRoute =
  AuthenticatedDashboardUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardUsersRoute,
  } as any)
const AuthenticatedDashboardArticlesNewRoute =
  AuthenticatedDashboardArticlesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardArticlesRoute,
  } as any)
const AuthenticatedDashboardArticlesIdEditRoute =
  AuthenticatedDashboardArticlesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedDashboardArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/dashboard/ai-draft': typeof AuthenticatedDashboardAiDraftRoute
  '/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/dashboard/articles': typeof AuthenticatedDashboardArticlesRouteWithChildren
  '/dashboard/users': typeof AuthenticatedDashboardUsersRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/users/$id': typeof AuthenticatedDashboardUsersIdRoute
  '/dashboard/articles/': typeof AuthenticatedDashboardArticlesIndexRoute
  '/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/dashboard/ai-draft': typeof AuthenticatedDashboardAiDraftRoute
  '/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/dashboard/users/$id': typeof AuthenticatedDashboardUsersIdRoute
  '/dashboard/articles': typeof AuthenticatedDashboardArticlesIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
  '/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/privacy': typeof PrivacyRoute
  '/prompts': typeof PromptsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/_authenticated/dashboard/ai-draft': typeof AuthenticatedDashboardAiDraftRoute
  '/_authenticated/dashboard/ai-tools': typeof AuthenticatedDashboardAiToolsRoute
  '/_authenticated/dashboard/articles': typeof AuthenticatedDashboardArticlesRouteWithChildren
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/articles/new': typeof AuthenticatedDashboardArticlesNewRoute
  '/_authenticated/dashboard/users/$id': typeof AuthenticatedDashboardUsersIdRoute
  '/_authenticated/dashboard/articles/': typeof AuthenticatedDashboardArticlesIndexRoute
  '/_authenticated/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
  '/_authenticated/dashboard/articles/$id/edit': typeof AuthenticatedDashboardArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-standards'
    | '/privacy'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/dashboard'
    | '/guides/$slug'
    | '/guides/'
    | '/dashboard/ai-draft'
    | '/dashboard/ai-tools'
    | '/dashboard/articles'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/articles/new'
    | '/dashboard/users/$id'
    | '/dashboard/articles/'
    | '/dashboard/users/'
    | '/dashboard/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-standards'
    | '/privacy'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/guides/$slug'
    | '/guides'
    | '/dashboard/ai-draft'
    | '/dashboard/ai-tools'
    | '/dashboard'
    | '/dashboard/articles/new'
    | '/dashboard/users/$id'
    | '/dashboard/articles'
    | '/dashboard/users'
    | '/dashboard/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-standards'
    | '/privacy'
    | '/prompts'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/_authenticated/dashboard'
    | '/guides/$slug'
    | '/guides/'
    | '/_authenticated/dashboard/ai-draft'
    | '/_authenticated/dashboard/ai-tools'
    | '/_authenticated/dashboard/articles'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/articles/new'
    | '/_authenticated/dashboard/users/$id'
    | '/_authenticated/dashboard/articles/'
    | '/_authenticated/dashboard/users/'
    | '/_authenticated/dashboard/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EditorialStandardsRoute: typeof EditorialStandardsRoute
  PrivacyRoute: typeof PrivacyRoute
  PromptsRoute: typeof PromptsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/articles': {
      id: '/_authenticated/dashboard/articles'
      path: '/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-tools': {
      id: '/_authenticated/dashboard/ai-tools'
      path: '/ai-tools'
      fullPath: '/dashboard/ai-tools'
      preLoaderRoute: typeof AuthenticatedDashboardAiToolsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-draft': {
      id: '/_authenticated/dashboard/ai-draft'
      path: '/ai-draft'
      fullPath: '/dashboard/ai-draft'
      preLoaderRoute: typeof AuthenticatedDashboardAiDraftRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users/': {
      id: '/_authenticated/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardUsersRoute
    }
    '/_authenticated/dashboard/articles/': {
      id: '/_authenticated/dashboard/articles/'
      path: '/'
      fullPath: '/dashboard/articles/'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardArticlesRoute
    }
    '/_authenticated/dashboard/users/$id': {
      id: '/_authenticated/dashboard/users/$id'
      path: '/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIdRouteImport
      parentRoute: typeof AuthenticatedDashboardUsersRoute
    }
    '/_authenticated/dashboard/articles/new': {
      id: '/_authenticated/dashboard/articles/new'
      path: '/new'
      fullPath: '/dashboard/articles/new'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardArticlesRoute
    }
    '/_authenticated/dashboard/articles/$id/edit': {
      id: '/_authenticated/dashboard/articles/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/articles/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardArticlesIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardArticlesRoute
    }
  }
}

interface AuthenticatedDashboardArticlesRouteChildren {
  AuthenticatedDashboardArticlesNewRoute: typeof AuthenticatedDashboardArticlesNewRoute
  AuthenticatedDashboardArticlesIndexRoute: typeof AuthenticatedDashboardArticlesIndexRoute
  AuthenticatedDashboardArticlesIdEditRoute: typeof AuthenticatedDashboardArticlesIdEditRoute
}

const AuthenticatedDashboardArticlesRouteChildren: AuthenticatedDashboardArticlesRouteChildren =
  {
    AuthenticatedDashboardArticlesNewRoute:
      AuthenticatedDashboardArticlesNewRoute,
    AuthenticatedDashboardArticlesIndexRoute:
      AuthenticatedDashboardArticlesIndexRoute,
    AuthenticatedDashboardArticlesIdEditRoute:
      AuthenticatedDashboardArticlesIdEditRoute,
  }

const AuthenticatedDashboardArticlesRouteWithChildren =
  AuthenticatedDashboardArticlesRoute._addFileChildren(
    AuthenticatedDashboardArticlesRouteChildren,
  )

interface AuthenticatedDashboardUsersRouteChildren {
  AuthenticatedDashboardUsersIdRoute: typeof AuthenticatedDashboardUsersIdRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
}

const AuthenticatedDashboardUsersRouteChildren: AuthenticatedDashboardUsersRouteChildren =
  {
    AuthenticatedDashboardUsersIdRoute: AuthenticatedDashboardUsersIdRoute,
    AuthenticatedDashboardUsersIndexRoute:
      AuthenticatedDashboardUsersIndexRoute,
  }

const AuthenticatedDashboardUsersRouteWithChildren =
  AuthenticatedDashboardUsersRoute._addFileChildren(
    AuthenticatedDashboardUsersRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAiDraftRoute: typeof AuthenticatedDashboardAiDraftRoute
  AuthenticatedDashboardAiToolsRoute: typeof AuthenticatedDashboardAiToolsRoute
  AuthenticatedDashboardArticlesRoute: typeof AuthenticatedDashboardArticlesRouteWithChildren
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAiDraftRoute: AuthenticatedDashboardAiDraftRoute,
    AuthenticatedDashboardAiToolsRoute: AuthenticatedDashboardAiToolsRoute,
    AuthenticatedDashboardArticlesRoute:
      AuthenticatedDashboardArticlesRouteWithChildren,
    AuthenticatedDashboardUsersRoute:
      AuthenticatedDashboardUsersRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  PrivacyRoute: PrivacyRoute,
  PromptsRoute: PromptsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
